# FROM node:17

# # Create app directory
# WORKDIR /app

# # Install app dependencies
# # A wildcard is used to ensure both package.json AND package-lock.json are copied
# # where available (npm@5+)
# COPY package*.json ./
# COPY tsconfig*.json ./

# # Bundle app source
# COPY . .

# RUN npm ci --quiet && npm run build

# EXPOSE 8080

# CMD [ "node", "dist/bin/www.js" ]