# version: "3.9"
# services:
#   bouncer-data:
#     image: public.ecr.aws/w0f5g4k6/javaweb:latest
#     # image: 0xkomada/bouncer-data
#     depends_on:
#       - redis
#     links:
#       - redis
#     ports:
#       - 3010:3010
#   redis:
#     image: redis
#     command: ["redis-server", "--appendonly", "yes"]
#     volumes:
#       - ./redis_data:/data
#     expose:
#       - 6379
